import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/footer/Footer';
import { TopMenu } from '@/components/ui/top-menu/TopMenu';
import ThemeProvider from '../components/ui/themeProvider/themeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SwaplyAr | Pasar dólares de PayPal a pesos argentinos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white text-black dark:bg-gray-900 dark:text-white`}
      >
        <ThemeProvider>
          <TopMenu />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
