// /app/layout.tsx

import type { Metadata } from 'next';
import Footer from '@/components/footer/Footer';
import { TopMenu } from '@/components/ui/top-menu/TopMenu';
import ThemeProvider from '../components/ui/theme-Provider/themeProvider';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';
import { inter } from '@/config/fonts/fonts';
import { MarginProvider } from '@/context/MarginContext';
import './globals.css';

export const metadata: Metadata = {
  title: 'SwaplyAr | Pasar dólares de PayPal a pesos argentinos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = localStorage.getItem('theme');
                const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                const isDark = theme === 'dark' || (!theme && systemPrefersDark);
                isDark ? document.documentElement.classList.add('dark') : document.documentElement.classList.remove('dark');
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${inter.className} bg-white text-lightText dark:bg-lightText dark:text-darkText`}
      >
        <ThemeProvider>
          <MarginProvider>
          <SpeedInsights />
          <Analytics />
          <TopMenu />
          {children}
          <Footer />
          </MarginProvider>

        </ThemeProvider>
      </body>
    </html>
  );
}
