import { System } from '@/types/data';
import {
  BankDarkImg,
  BankImg,
  PayoneerEurDarkImg,
  PayoneerEurImg,
  PayoneerUsdDarkImg,
  PayoneerUsdImg,
  PaypalDarkImg,
  PaypalImg,
  WiseEurDarkImg,
  WiseEurImg,
  WiseUsdDarkImg,
  WiseUsdImg,
} from '@/utils/assets/imgDatabaseCloudinary';

export const systems: System[] = [
  {
    id: 'paypal',
    name: 'PayPal',
    logo: PaypalImg,
    logoDark: PaypalDarkImg,
    isDisabled: false,
    coin: 'USD',
    paymentMethod: 'paypal',
  },
  {
    id: 'payoneer_usd',
    name: 'Payoneer',
    logo: PayoneerUsdImg,
    logoDark: PayoneerUsdDarkImg,
    isDisabled: false,
    coin: 'USD',
    paymentMethod: 'payoneer',
  },
  {
    id: 'payoneer_eur',
    name: 'Payoneer',
    logo: PayoneerEurImg,
    logoDark: PayoneerEurDarkImg,
    isDisabled: false,
    coin: 'EUR',
    paymentMethod: 'payoneer',
  },
  {
    id: 'bank',
    name: 'Bank',
    logo: BankImg,
    logoDark: BankDarkImg,
    isDisabled: false,
    coin: 'ARS',
    paymentMethod: 'ars',
  },
  {
    id: 'wise_usd',
    name: 'Wise',
    logo: WiseUsdImg,
    logoDark: WiseUsdDarkImg,
    isDisabled: false,
    coin: 'USD',
    paymentMethod: 'wise',
  },
  {
    id: 'wise_eur',
    name: 'Wise',
    logo: WiseEurImg,
    logoDark: WiseEurDarkImg,
    isDisabled: false,
    coin: 'EUR',
    paymentMethod: 'wise',
  },
];
