import { BlogPost } from '@/types/blogs/blog';
import { BlogImage1 } from './assets/img-database';

export const blogPosts: BlogPost[] = [
  {
    blog_id: '1',
    sub_title: 'PayPal',
    title: 'Introducción a React',
    body: 'React es una biblioteca de JavaScript para construir interfaces de usuario...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '2',
    sub_title: 'PayPal',
    title: 'Guía de Redux para Principiantes',
    body: 'Redux es una biblioteca para manejar el estado de las aplicaciones...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '3',
    sub_title: 'PayPal',
    title: 'Cómo mejorar el rendimiento en React',
    body: 'Optimizar el rendimiento en React es crucial para aplicaciones grandes...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '4',
    sub_title: 'PayPal',
    title: 'Hooks de React: useState y useEffect',
    body: 'Los hooks permiten usar el estado y otras características de React sin escribir una clase...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '5',
    sub_title: 'PayPal',
    title: 'Styled Components en React',
    body: 'Styled Components permite escribir CSS en JavaScript para estilizar componentes...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '6',
    sub_title: 'PayPal',
    title: 'Introducción a TypeScript con React',
    body: 'TypeScript mejora la calidad del código en React con tipado estático...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '7',
    sub_title: 'PayPal',
    title: 'React Router: Navegación',
    body: 'React Router permite la navegación en aplicaciones de una sola página...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '8',
    sub_title: 'PayPal',
    title: 'Lazy Loading en React',
    body: 'Lazy Loading ayuda a mejorar el rendimiento cargando componentes solo cuando se necesitan...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '9',
    sub_title: 'PayPal',
    title: 'React con GraphQL',
    body: 'GraphQL permite realizar consultas más eficientes en aplicaciones React...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '10',
    sub_title: 'PayPal',
    title: 'Autenticación en React con Firebase',
    body: 'Firebase proporciona autenticación fácil de implementar en aplicaciones React...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '11',
    sub_title: 'PayPal',
    title: 'React y Tailwind CSS',
    body: 'Tailwind CSS facilita la creación de diseños modernos en React...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '12',
    sub_title: 'PayPal',
    title: 'Uso de Context API en React',
    body: 'Context API permite compartir datos en la aplicación sin prop drilling...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '13',
    sub_title: 'PayPal',
    title: 'Testing en React con Jest y React Testing Library',
    body: 'Realizar pruebas en React ayuda a prevenir errores en producción...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '14',
    sub_title: 'PayPal',
    title: 'SSR vs CSR en React',
    body: 'La diferencia entre Server-Side Rendering y Client-Side Rendering es crucial para el rendimiento...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
  {
    blog_id: '15',
    sub_title: 'PayPal',
    title: 'Deploy de una aplicación React',
    body: 'Existen varias opciones para desplegar aplicaciones React, como Vercel y Netlify...',
    url_image: BlogImage1,
    ver: 'Más información',
    created_at: new Date().toISOString(),
  },
];
