// import { BlogPost } from '@/types/blogs/blog';
// import { BlogImage1 } from './assets/img-database';

// export const blogPosts: BlogPost[] = [
//   {
//     blog_id: '1',
//     sub_title: 'PayPal',
//     title: 'Introducción a React',
//     body: 'React es una biblioteca de JavaScript para construir interfaces de usuario...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '2',
//     sub_title: 'PayPal',
//     title: 'Guía de Redux para Principiantes',
//     body: 'Redux es una biblioteca para manejar el estado de las aplicaciones...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '3',
//     sub_title: 'PayPal',
//     title: 'Cómo mejorar el rendimiento en React',
//     body: 'Optimizar el rendimiento en React es crucial para aplicaciones grandes...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '4',
//     sub_title: 'PayPal',
//     title: 'Hooks de React: useState y useEffect',
//     body: 'Los hooks permiten usar el estado y otras características de React sin escribir una clase...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '5',
//     sub_title: 'PayPal',
//     title: 'Styled Components en React',
//     body: 'Styled Components permite escribir CSS en JavaScript para estilizar componentes...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '6',
//     sub_title: 'PayPal',
//     title: 'Introducción a TypeScript con React',
//     body: 'TypeScript mejora la calidad del código en React con tipado estático...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '7',
//     sub_title: 'PayPal',
//     title: 'React Router: Navegación',
//     body: 'React Router permite la navegación en aplicaciones de una sola página...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '8',
//     sub_title: 'PayPal',
//     title: 'Lazy Loading en React',
//     body: 'Lazy Loading ayuda a mejorar el rendimiento cargando componentes solo cuando se necesitan...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '9',
//     sub_title: 'PayPal',
//     title: 'React con GraphQL',
//     body: 'GraphQL permite realizar consultas más eficientes en aplicaciones React...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '10',
//     sub_title: 'PayPal',
//     title: 'Autenticación en React con Firebase',
//     body: 'Firebase proporciona autenticación fácil de implementar en aplicaciones React...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '11',
//     sub_title: 'PayPal',
//     title: 'React y Tailwind CSS',
//     body: 'Tailwind CSS facilita la creación de diseños modernos en React...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '12',
//     sub_title: 'PayPal',
//     title: 'Uso de Context API en React',
//     body: 'Context API permite compartir datos en la aplicación sin prop drilling...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '13',
//     sub_title: 'PayPal',
//     title: 'Testing en React con Jest y React Testing Library',
//     body: 'Realizar pruebas en React ayuda a prevenir errores en producción...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '14',
//     sub_title: 'PayPal',
//     title: 'SSR vs CSR en React',
//     body: 'La diferencia entre Server-Side Rendering y Client-Side Rendering es crucial para el rendimiento...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '15',
//     sub_title: 'PayPal',
//     title: 'Deploy de una aplicación React',
//     body: 'Existen varias opciones para desplegar aplicaciones React, como Vercel y Netlify...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '16',
//     sub_title: 'PayPal',
//     title: 'State Management en React con Recoil',
//     body: 'Recoil es una biblioteca para el manejo del estado global en React...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '17',
//     sub_title: 'PayPal',
//     title: 'Optimización de imágenes en React',
//     body: 'Optimizar las imágenes es importante para mejorar el rendimiento de una aplicación React...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '18',
//     sub_title: 'PayPal',
//     title: 'Integración de Stripe en React para pagos',
//     body: 'Stripe permite realizar pagos de manera sencilla en aplicaciones React...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '19',
//     sub_title: 'PayPal',
//     title: 'Patrón de Diseño: Componente Contenedor en React',
//     body: 'El patrón de diseño de contenedor ayuda a estructurar componentes de manera eficiente...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '20',
//     sub_title: 'PayPal',
//     title: 'Documentación de componentes con Storybook',
//     body: 'Storybook es una herramienta para documentar y probar componentes de UI...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '21',
//     sub_title: 'PayPal',
//     title: 'Estrategias de caché en React con SWR',
//     body: 'SWR es una librería para la gestión de caché en aplicaciones React...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '22',
//     sub_title: 'PayPal',
//     title: 'Mejorando la accesibilidad en React',
//     body: 'La accesibilidad es crucial para garantizar que nuestras aplicaciones sean usables para todos...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '23',
//     sub_title: 'PayPal',
//     title: 'Integración de Google Maps en React',
//     body: 'Google Maps API se puede integrar fácilmente en aplicaciones React para mostrar mapas...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '24',
//     sub_title: 'PayPal',
//     title: 'Diseño Responsive con React',
//     body: 'El diseño responsive es esencial para aplicaciones que funcionen bien en diferentes dispositivos...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '25',
//     sub_title: 'PayPal',
//     title: 'Introducción a GraphQL',
//     body: 'GraphQL es un lenguaje de consulta para APIs que permite obtener solo los datos necesarios... ',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '26',
//     sub_title: 'PayPal',
//     title: 'Automatización de pruebas con Cypress',
//     body: 'Cypress es una herramienta para hacer pruebas end-to-end de aplicaciones web... ',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '27',
//     sub_title: 'PayPal',
//     title: 'Introducción a los Microservicios con Node.js',
//     body: 'Los microservicios permiten dividir las aplicaciones en pequeños servicios independientes... ',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '28',
//     sub_title: 'PayPal',
//     title: 'Optimización de la carga inicial en React',
//     body: 'La carga inicial de una aplicación React puede ser optimizada para mejorar la experiencia del usuario...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '29',
//     sub_title: 'PayPal',
//     title: 'Integración de WebSockets en React',
//     body: 'Los WebSockets permiten una comunicación bidireccional en tiempo real entre el cliente y el servidor...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '30',
//     sub_title: 'PayPal',
//     title: 'Patrón de Diseño: Presentacional y Contenedor',
//     body: 'Este patrón ayuda a separar los componentes presentacionales de los componentes que gestionan la lógica...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
//   {
//     blog_id: '31',
//     sub_title: 'PayPal',
//     title: 'Uso de TypeScript con React Hooks',
//     body: 'TypeScript se puede usar con los hooks de React para proporcionar tipado estático y mejorar la calidad del código...',
//     url_image: BlogImage1,
//     ver: 'Más información',
//     created_at: new Date().toISOString(),
//   },
// ];
